### ISSUE TITLE
PicTalk auto-upload active?

### ISSUE THREAD

**Issue by K4KDR** [f4gkr/PicTalk#13]
During previous passes, I ran an array of Windows SDR & decoder tools on a second computer in parallel with PicTalk on a linux computer.  One of those Windows apps was the SiDS uploader from DK3WN.  Packets decoded in Windows and uploaded via the DK3WN decoder would be immediately reflected on my profile page.

On tonight's pass, I did NOT run the Windows DK3WN SiDS uploader.  PicTalk on linux decoded 64 packets but I can find no indication on the local linux PC (logs, etc.) nor on the PicSat website that those packets were uploaded to the project team.

At this time (23-Feb-2018) is PicTalk programmed to automatically upload decoded packets?

If, so, how can we tell if that was successful?

If not, of course that's fine & the newly decoded packets can be easily uploaded manually on the website.

Thank you!

**Comment by f4gkr** [comment]
The packet upload is active and lacking report to the user.... if you log in Picsat website you should see the frames in your profile. 
Definitively have to display the successful upload of the frames !
By the way, they are still supposed to be stored in the PicTalk-data folder, in file "decodedframes.txt"

**Comment by f4gkr** [comment]
Following a comment received by mail from Albert PD0OXW, information report to user is clearly missing and is a "must do"

**Comment by f4gkr** [comment]
Michel F5WK confirms successfull reporting of all received frames

**Comment by f4gkr** [comment]
During the demo yesterday at Electrolab, successfully submitted more than 200 frames to server
