### ISSUE TITLE
ubuntu bug dependencies QtConcurrent

### ISSUE THREAD

**Issue by darcosion** [f4gkr/PicTalk#18]
Hello, i have a compilation issue Qt.

With Qt4 i have an issue with QtConcurrent : 
`../qwt/qwt_plot_rasteritem.cpp:21:24: fatal error: QtConcurrent: Aucun fichier ou dossier de ce type
`

I think it could be useful to specified the QT version in the pro configuration file like this : 

`if(QT_VERSION == 4) {
   QT += concurrent
}` 

I think that could resolve some problems in compilation, for me, I specified the utilisation of QT5 compilator who work.

**Comment by f4gkr** [comment]
Users will be warned that Qt5 is required

lessThan(QT_MAJOR_VERSION, 5): error("requires Qt 5")

added in .pro file

2018-02-24 12:21 GMT+01:00 P. Tisserand <notifications@github.com>:
