### ISSUE TITLE
libgps-dev is also a dependency

### ISSUE THREAD

**Issue by K4KDR** [f4gkr/PicTalk#2]
Hello!  Thanks for all the work to produce such a nice GUI.

When compiling on Ubuntu 16.04 linux (64-bit), I received the following:

```
In file included from main.cpp:41:0:
hardware/gpdsd.h:38:17: fatal error: gps.h: No such file or directory
compilation terminated.
Makefile:2687: recipe for target 'main.o' failed
make: *** [main.o] Error 1
```

... apparently "libgps-dev" is required as the compile was successful after running:

`sudo apt-get install libgps-dev`

**Comment by f4gkr** [comment]
Yes... thanks for the bug report, just saw it too here.
I am about to push the fix within a minute, stay tuned ;-)

2018-02-20 17:45 GMT+01:00 K4KDR <notifications@github.com>:

**Comment by f4gkr** [comment]
Just done ! please update your repo

2018-02-20 17:47 GMT+01:00 Sylvain AZARIAN <sylvain.azarian@gmail.com>:

**Comment by f4gkr** [comment]
Let me know so I can close this one

**Comment by K4KDR** [comment]
Perhaps someone who does NOT have **libgps-dev** installed could verify that the dependency is no longer required?  (I would prefer to not reverse my configuration since it is now working!)  :)

**Comment by f4gkr** [comment]
Sure !
BTW I have to redo a complete setup following some comments,
thanks

2018-02-20 18:14 GMT+01:00 K4KDR <notifications@github.com>:
