### ISSUE TITLE
Errors when compiling with python 3.6 option (under Ubuntu 22.04)

### ISSUE THREAD

**Issue by f6bvp** [f4gkr/PicTalk#28]
Hi Sylvain,

I tried to update pictalk.pro with python3.6 as suggested in README but I got compilations warnings and errors.

I wonder if there are any updates available for more recent python versions like 3.10 ?

73 de Bernard, f6bvp / ai7bg

**Comment by f4gkr** [comment]
Salut Bernard !

I have not worked on this for a while. Let me come back from my vacation
and I will. Probably next week end.

73
Sylvain f4gkr

**Comment by f6bvp** [comment]
TKS Sylvain.
No hurry, take care and have a nice holliday.
73 de Bernard f6bvp

**Comment by f4gkr** [comment]
Can you check with the following in the pictalk.pro : 
replace the linux { .... } (from lines 50 to 66) with : 

```
linux {
    # using directly the python3-config 
    LIBS += $$system("python3-config --libs")
    QMAKE_CFLAGS += $$system("python3-config --cflags")
    INCLUDEPATH += $$system("python3-config --includes |cut -c 3-")
    DESTDIR = $$PWD/bin
    contains( QMAKE_HOST.arch, arm.* ):{
        #specific instructions for RPiCompile

    } else {
        # generic Linux compile...
        DEFINES += USE_SSE2
        QMAKE_CXXFLAGS  += -msse2
        QMAKE_CFLAGS += -msse2
    }
    LIBS += -lhidapi-hidraw
}
```

**Comment by f6bvp** [comment]
Applied to pictalk.pro

Still a bunch of Warnings and error.
Only last one reported here :


       |                       ^~~~
qwt/qwt_text.h:142:41: warning: ‘QString::null’ is deprecated: use 
QString() [-Wdeprecated-declarations]
   142 |     QwtText( const QString & = QString::null,
       |                                         ^~~~
../../../include/x86_64-linux-gnu/qt5/QtCore/qstring.h:954:23: note: 
declared here
   954 |     static const Null null;
       |                       ^~~~
g++ -c -pipe -std=c++11 -msse2 -O2 -Wall -Wextra -D_REENTRANT -fPIC 
-DBUILD_DATE="\"20230429\"" -DUSE_SSE2 -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB 
-DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB 
-DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Ihttpserver 
-I../../../include/python3.10 -I-I/usr/include/python3.10 
-I../../../include/x86_64-linux-gnu/qt5 
-I../../../include/x86_64-linux-gnu/qt5/QtMultimedia 
-I../../../include/x86_64-linux-gnu/qt5/QtOpenGL 
-I../../../include/x86_64-linux-gnu/qt5/QtPrintSupport 
-I../../../include/x86_64-linux-gnu/qt5/QtSvg 
-I../../../include/x86_64-linux-gnu/qt5/QtWidgets 
-I../../../include/x86_64-linux-gnu/qt5/QtGui 
-I../../../include/x86_64-linux-gnu/qt5/QtNetwork 
-I../../../include/x86_64-linux-gnu/qt5/QtCore -I. 
-I../../../lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o 
qwt_compass_rose.o qwt/qwt_compass_rose.cpp
qwt/qwt_compass_rose.cpp: In function ‘QPointF qwtIntersection(QPointF, 
QPointF, QPointF, QPointF)’:
qwt/qwt_compass_rose.cpp:22:25: warning: ‘QLineF::IntersectType 
QLineF::intersect(const QLineF&, QPointF*) const’ is deprecated: Use 
intersects() instead [-Wdeprecated-declarations]
    22 |     if ( line1.intersect( line2, &pos ) == QLineF::NoIntersection )
       |          ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
In file included from 
../../../include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h:47,
                  from 
../../../include/x86_64-linux-gnu/qt5/QtGui/qbrush.h:49,
                  from 
../../../include/x86_64-linux-gnu/qt5/QtGui/qpalette.h:46,
                  from qwt/qwt_compass_rose.h:14,
                  from qwt/qwt_compass_rose.cpp:10:
../../../include/x86_64-linux-gnu/qt5/QtCore/qline.h:256:19: note: 
declared here
   256 |     IntersectType intersect(const QLineF &l, QPointF 
*intersectionPoint) const;
       |                   ^~~~~~~~~
qwt/qwt_compass_rose.cpp: In static member function ‘static void 
QwtSimpleCompassRose::drawRose(QPainter*, const QPalette&, const 
QPointF&, double, double, double, int, int, double)’:
qwt/qwt_compass_rose.cpp:179:26: error: aggregate ‘QPainterPath 
darkPath’ has incomplete type and cannot be defined
   179 |             QPainterPath darkPath;
       |                          ^~~~~~~~
qwt/qwt_compass_rose.cpp:187:26: error: aggregate ‘QPainterPath 
lightPath’ has incomplete type and cannot be defined
   187 |             QPainterPath lightPath;
       |                          ^~~~~~~~~
make: *** [Makefile:11898 : qwt_compass_rose.o] Erreur 1


Le 28/04/2023 à 21:47, Sylvain AZARIAN a écrit :

**Comment by f4gkr** [comment]
Bonjour,

Ok... much more complicated than expected but probably got it.
I have now a "compiling &starting" PicTalk on Ubuntu 22.04 with Python
3.10. Lots of changes in the code :
- Updated QWT to latest version
- Added specific HID files to have the Funcube support compiled

[image: image.png]

The program has not been tested "on air"

sylvain
