### ISSUE TITLE
python3 versions of scipy & requests required

### ISSUE THREAD

**Issue by K4KDR** [f4gkr/PicTalk#3]
On Ubuntu 16.04 (64-bit), even though GUI launched successfully, I noticed the following in the terminal window:

**ImportError: No module named 'scipy'**

... even though the Ubuntu repository version of python3-scipy was already installed:

```
k4kdr@:~/PicTalk$ apt-cache policy python3-scipy
python3-scipy:
  Installed: 0.17.0-1
  Candidate: 0.17.0-1
  Version table:
 *** 0.17.0-1 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        100 /var/lib/dpkg/status
```

This was corrected by running:

`pip3 install scipy`

======

After applying the above fix, saw in the terminal window:

**ImportError: No module named 'requests'**

... this was corrected by running:

`pip3 install requests`

======

After applying the above, the terminal window shows much more feedback than it did when the "No module" errors were being seen:

```
k4kdr@:~/PicTalk$ ./bin/pictalk
Found Rafael Micro R820T tuner
 Tuner type: 5  min_tuner_freq= 24000000  max_tuner_freq= 1766000000
 gain range :  0  to  49.6
 manufacturer :: Realtek
 product :: RTL2838UHIDIR
 serial :: 00000001
Exact sample rate is: 2200000.014570 Hz
Web server listening on port 8001
Controller::run() 
transition from  0  to  1
using Python : "/home/k4kdr/PicTalk/bin/python/decodeZ3.py"
starting PythonDecoder::run()
starting python
Starting ZMQ publisher…
Started ZMQ publisher.
Connecting to PicTalk
Starting Main Thread
Connected to PicTalk.
python ends
Sending Picsat RX frequency
```

**Comment by f4gkr** [comment]
You are right ... Forgot the requests module
What you see looks good, the phython is correctly working

**Comment by K4KDR** [comment]
Great!  Will there be doppler frequency adjustment during a pass?  I assume this is a hands-off GUI?  

Also, is there real-time upload of decoded frames?  Not sure what to expect from the app, exactly.

Thanks!

**Comment by f4gkr** [comment]
Yes the doppler correction is automatic but you have to upload manually the
frames for today. You will find them also in the pictalk subfolder in your
home.

The auto upload is under work

Sylvain

**Comment by K4KDR** [comment]
Thank you, sir!
