### ISSUE TITLE
Dependences from Debian 9

### ISSUE THREAD

**Issue by lu9cbl** [f4gkr/PicTalk#4]
Hi! thanks for your work!!! i'm trying to install it from the deb package, but in the dependences when i'm put the "apt-get -f install" don't install nothing. If i'm try to search the packages individually, i'm found all except the libpython3.6-dev.

All others found ok (libfftw3-3 qt5-default libzmq3-dev libhidapi-hidraw0 python3-zmq python3-scipy python3-numpy).

#dpkg -i ./pictalk_1.0.0_amd64.deb 
dpkg: problemas de dependencias impiden la configuración de pictalk:
 pictalk depende de libfftw3-3; sin embargo:
  El paquete `libfftw3-3' no está instalado.
 pictalk depende de qt5-default (>= 5.5); sin embargo:
  El paquete `qt5-default' no está instalado.
 pictalk depende de libzmq3-dev; sin embargo:
  El paquete `libzmq3-dev' no está instalado.
 pictalk depende de libhidapi-hidraw0; sin embargo:
  El paquete `libhidapi-hidraw0' no está instalado.
 pictalk depende de python3-zmq; sin embargo:
  El paquete `python3-zmq' no está instalado.
 pictalk depende de python3-scipy; sin embargo:
  El paquete `python3-scipy' no está instalado.
 pictalk depende de python3-numpy; sin embargo:
  El paquete `python3-numpy' no está instalado.
 pictalk depende de libpython3.6-dev; sin embargo:
  El paquete `libpython3.6-dev' no está instalado.

**Comment by K4KDR** [comment]
** Better to get reply from the author, but FYI...

On my Ubuntu 16.04 machine, I don't see any listing for a **libpython3.6-dev** as being available:

```
k4kdr@:~/PicTalk$ apt-cache search libpython3
libpython3-all-dbg - package depending on all supported Python 3 debugging packages
libpython3-all-dev - package depending on all supported Python 3 development packages
libpython3-dbg - debug build of the Python 3 Interpreter (version 3.5)
libpython3-dev - header files and a static library for Python (default)
libpython3-stdlib - interactive high-level object-oriented language (default python3 version)
libpython3.5 - Shared Python runtime library (version 3.5)
libpython3.5-dbg - Debug Build of the Python Interpreter (version 3.5)
libpython3.5-dev - Header files and a static library for Python (v3.5)
libpython3.5-minimal - Minimal subset of the Python language (version 3.5)
libpython3.5-stdlib - Interactive high-level object-oriented language (standard library, version 3.5)
libpython3.5-testsuite - Testsuite for the Python standard library (v3.5)
```

... also, I compiled from source and changed the pictalk.pro file to use v3.5 python since that is what was on my system.

**Comment by f4gkr** [comment]
Buenas !

The github and binary will be updated (tomorrow morning/Paris time) for
Python 3.5 following the number of folks asking !

sylvain

2018-02-20 20:15 GMT+01:00 K4KDR <notifications@github.com>:

**Comment by lu9cbl** [comment]
Thanks! i will try it in that way.

**Comment by f4gkr** [comment]
Changes to Python 3.5 now available, please let me know
