### ISSUE TITLE
Packets seen but not decoded

### ISSUE THREAD

**Issue by K4KDR** [f4gkr/PicTalk#5]
Granted a low pass here (< 10 degrees elevation), but a strong signal was received from numerous packets.  However, while there was activity in the terminal window (see below), no packets appeared to decode.  

Here is the terminal window content that was seen when a strong enough packet was received:

```
Proccessing Data from point 0 to 2183, with slow speed:
..1..with delay = 4 ms
 state transition from  "sFrameStart"  to  "sFrameEnds"
 state transition from  "sFrameEnds"  to  "sSearchFrame"
..3..with delay = 27 ms
..4..with delay = 523 ms
..5..with delay = 612 ms
..9..with delay = 612 ms and biterate 9600
..1..with delay = 2 ms
..3..with delay = 8 ms
..4..with delay = 312 ms
..5..with delay = 368 ms
..9..with delay = 368 ms and biterate 1200
 state transition from  "sSearchFrame"  to  "sFrameStart"
 state transition from  "sFrameStart"  to  "sFrameEnds"
 state transition from  "sFrameEnds"  to  "sSearchFrame"
 state transition from  "sSearchFrame"  to  "sFrameStart"
 state transition from  "sFrameStart"  to  "sFrameEnds"
 state transition from  "sFrameEnds"  to  "sSearchFrame"
```

... a more favorable pass is upcoming, so perhaps the higher signal strength will produce decodes.

**Comment by K4KDR** [comment]
Update:  

 PicTalk decoded several packets on the higher pass here tonight.   Uploaded to the website under user "K4KDR" as **2018-02-21--0242--k4kdr-pictalkframes.txt**

Screen shots from the capture at:  https://twitter.com/scott23192/status/966148058890342400

**Comment by f4gkr** [comment]
Probably related to issue reported by F5WK on formatting to hex some bytes from the frames... it is fixed and source just updated
