### ISSUE TITLE
Folder Names

### ISSUE THREAD

**Issue by K4KDR** [f4gkr/PicTalk#6]
Perhaps by design, but a possible point of confusion:

While the "git clone" method to obtain the software creates the folder "**PicTalk**", I notice that a "**pictalk**" folder has also been created in my home directory.   

The "pictalk" folder contains a single file: pictalk.conf

You may wish to either combine these into a single folder, or at least draw attention to this situation in the README.

**Comment by f4gkr** [comment]
We need a folder to store the received frames and preferences (pictalk.conf). In Linux the file location has to be in the home directory because of file access policy. Currently this folder should contain up to three files: 
- a log 
- a settings file (will be important for saving some parameters for the next release with autoupload of the frames)
- a "received frames" file

**Comment by K4KDR** [comment]
Thank you.  I just wanted to mention that identical folder names (except for uppercase/lowercase) could be confusing, and also will **not** work on a Windows system where file/folder names are not distinctive by case.  On Linux, they do represent two different folders, so we can just be aware of that and be fine.

**Comment by f4gkr** [comment]
You are more than right ! This must be changed. Any suggestion ?

2018-02-21 15:40 GMT+01:00 K4KDR <notifications@github.com>:

**Comment by K4KDR** [comment]
If the location can be under the app's root folder, then you often see things like:

`~/PicTalk/data`

... if a completely separate folder is required OUTSIDE of the app's main folder structure, then something like the following would be easily recognizable:

`~/PicTalk-data`

**Comment by f4gkr** [comment]
ok for ~/PicTalk-data
good suggestion, thanks

2018-02-21 15:48 GMT+01:00 K4KDR <notifications@github.com>:

**Comment by f4gkr** [comment]
changed as suggested to PicTalk-data
available in source distro only so far.
