### ISSUE TITLE
zmqserver error

### ISSUE THREAD

**Issue by F0FYF** [f4gkr/PicTalk#8]
Bonjour Sylvain
J'ai l'erreur suivante lors de la compile de PicTalk : 

> zmqserver.o : Dans la fonction « ZmqServer::run() » :
> zmqserver.cpp:(.text+0x126) : référence indéfinie vers « zmq_ctx_new »
> zmqserver.cpp:(.text+0x2a4) : référence indéfinie vers « zmq_ctx_destroy »
> pythondecoder.o : Dans la fonction « ZmqPython::run() » :
> pythondecoder.cpp:(.text+0x9f2) : référence indéfinie vers « zmq_ctx_new »
> collect2: error: ld returned 1 exit status
> Makefile:839 : la recette pour la cible « bin/pictalk » a échouée
> make: *** [bin/pictalk] Erreur 1

J'ai bien la dernière version de zmq pourtant .. une idée ? 
Merci 

Jeff - F0FYF

**Comment by f4gkr** [comment]
Bonsoir,

Est ce que tu as installé la librairie

   - libczmq-dev ?

Sur quelle version de Linux compiles tu ?
merci

**Comment by F0FYF** [comment]
Re
Libczmq-dev est bien installé et je test sous xubuntu 16.04

J'ai en fait trouvé d'où ça venait .. j'ai mis à jour hidapi ( ma version était la 0.2.2 et il faut la 0.7 au minimum pour avoir la bonne librairie pour zeromq ) car j'avais un warning dessus lors de la compil et finallement, tout est passé et tout fonctionne.

Merci pour tout
Jeff - F0FYF

**Comment by f4gkr** [comment]
Ok merci
