### ISSUE TITLE
Latitide / Longitude Format?

### ISSUE THREAD

**Issue by K4KDR** [f4gkr/PicTalk#9]
Please forgive me if this has been addressed on social media or a README, but I could not find it.

What format should be used for the "Your latitude" & "Your longitude" boxes when prompted?

Thank you!

**Comment by f4gkr** [comment]
Bonjour

Good point... was too fast on this one. Format is decimal with letter at
the end, exactly like you can see in your picsat account.

Will add a tip on the window and update the code this morning my (Paris)
time

**Comment by f4gkr** [comment]
added to source just now
